# Generated by Django 3.1.7 on 2021-03-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
