# Generated by Django 3.1.7 on 2021-03-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210311_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_name',
            field=models.CharField(auto_created=True, blank=True, default=None, max_length=100, null=True),
        ),
    ]
